In [3]:
import os
import pcapy as p
from scapy.all import *
import matplotlib.pyplot as plt
import array

import pandas as pd
import glob
import struct
import numpy as np
import pcaps as pcaps

import pyusbus as us
import base64
import json

from CONVEX_JSON import *

In [17]:
df = pd.DataFrame(cvx).T.reset_index()
#df["PL"] = "b'"+df.payload+"'"
df["PL"] = df.payload.apply(lambda x: base64.b64decode(x ))
# basedf["PL"] =base64.b64decode(self.payloads[k][1:-1] + "========")
df["lst"] =  df.PL.apply(lambda x: pcaps.bin2array(x))
df["lenLST"] = df.lst.apply(lambda x: len(x))
df

/home/kelu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:5: DeprecationWarning: fromstring() is deprecated. Use frombytes() instead.
  """


index                        desc packet  \
0   07d644                      Depth5   3848   
1   0dcb54                      Seq1.3    182   
2   141e07                PreInitBoot3    228   
3   15a117   Packet 204 ./onoff.pcapng    204   
4   1e3a1f                PreInitBoot4    234   
5   251731  TGC-related-TBC-StartMaybe    192   
6   2929ce                       Init1    163   
7   2c7bb0             ConfirmDepth5.1   3854   
8   305582                   Seq1.4bis    184   
9   3763c0                      Seq1.7    190   
10  4ca6cd                      Seq1.1    238   
11  5ca4db                      Seq1.6    188   
12  5e81b8                      Depth2   1660   
13  7c0f48                PreInitBoot1    202   
14  7c5964                       Init2    172   
15  7f3fc5                       Init6    180   
16  8a32e0             ConfirmDepth5.2   3864   
17  8a88be                       Init3    174   
18  90ea99                      Depth0   3332   
19  9618a9           PreStopPacket-TBC   3674   
20  9885ce             ConfirmDepth1.3   2678   
21  a234f7                       Init4    176   
22  a7730e             ConfirmDepth2.1   2220   
23  afc305                      Depth3   2216   
24  b603cb                      Seq1.4    246   
25  c59d63                      Seq1.2    240   
26  ca4346                      Depth1   1540   
27  cd9d28                       Init5    178   
28  cf0b2b                      Seq1.5    186   
29  d343f9                PreInitBoot2    218   
30  db6a77                 StopAcq-TBC   3679   
31  e15e3b                      Depth4   2672   
32  e720a6             ConfirmDepth2.2   2228   
33  f4cd14             ConfirmDepth1.2   1560   
34  fea371             ConfirmDepth1.1   1545   

                                              payload  \
0   WlpaWgAAAAAAAAAAPMYSYCA0QIAAAAAAAAAAAAAAAAAAAA...   
1   WlpaWgAAAAAAAAAAAAAQswAAILMAADCzAABAswAAAAAAAA...   
2   WlpaWgAAAAAAAAAAAdIAIGDGASAAQAIgAEADIABABCAAQA...   
3   WlpaWg8HAwYwAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAA...   
4   WlpaWgAAAAAAAAAAgEt8IJBLfSCgS34gsEt/IAAAAAAAAA...   
5   WlpaWgAAAAAAAAAAAAACoAAAAAAAAAAAAAAAAAAAAAAAAA...   
6   WlpaWgAAAAAAAAAAGAAQAAUEEQAKBRIAAP8TAAAIFAABCR...   
7   WlpaWgAAAAAAAAAAFgAAcAQABKAAAAAAAAAAAAAAAAAAAA...   
8   WlpaWgAAAAAAAAAAAAAA0AAAAdAAAALQAAAD0AAABNAAAA...   
9   WlpaWgAAAAAAAAAA//900f//ddH//3bR//930f//eNH//3...   
10  WlpaWgAAAAAAAAAADIsSYLQtQIAAAAAAAAAAAAAAAAAAAA...   
11  WlpaWgAAAAAAAAAA///40P//+dD///rQ///70P///ND///...   
12  WlpaWgAAAAAAAAAAfCwhYLQbQIAAAAAAAAAAAAAAAAAAAA...   
13  WlpaWgAAAAAAAAAAAAABtAAAAAAAAAAAAAAAAAAAAAAAAA...   
14  WlpaWgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...   
15  WlpaWgAAAAAAAAAACgAAcAIABKAAAAAAAAAAAAAAAAAAAA...   
16  WlpaWgAAAAAAAAAAAAAA0AAAAdAAAALQAAAD0AAABNAAAA...   
17  WlpaWgAAAAAAAAAAAdIAIGDGASAAQAIgMEADIGBABCCQQA...   
18  WlpaWgAAAAAAAAAA+FgSYMAnQIAAAAAAAAAAAAAAAAAAAA...   
19  WlpaWg8HAwYwAAAAAAAAAAEAAAAEAAAAAAAAAAAAAAAAAA...   
20  WlpaWgAAAAAAAAAAEgAAcAIABKAAAAAAAAAAAAAAAAAAAA...   
21  WlpaWgAAAAAAAAAAAEx8IABMfSAATH4gAEx/IAAAAAAAAA...   
22  WlpaWgAAAAAAAAAAEAAAcAIABKAAAAAAAAAAAAAAAAAAAA...   
23  WlpaWgAAAAAAAAAAVMgwYOQPQIAAAAAAAAAAAAAAAAAAAA...   
24  WlpaWgAAAAAAAAAAAAAA0AAAAdAAAALQAAAD0AAABNAAAA...   
25  WlpaWgAAAAAAAAAAFAAAcAQABKAAAAAAAAAAAAAAAAAAAA...   
26  WlpaWgAAAAAAAAAA+FgSYLQhQIAAAAAAAAAAAAAAAAAAAA...   
27  WlpaWgAAAAAAAAAAXGISYNAOQIAAAAAAAAAAAAAAAAAAAA...   
28  WlpaWgAAAAAAAAAA//980P//fdD//37Q//9/0P//gND//4...   
29  WlpaWgAAAAAAAAAAPAAQAAUEEQAKBRIAAP8TAAAIFAABCR...   
30  WlpaWgAAAAAAAAAAAAABoAAAAAAAAAAAAAAAAAAAAAAAAA...   
31  WlpaWgAAAAAAAAAAfCwhYMAVQIAAAAAAAAAAAAAAAAAAAA...   
32  WlpaWgAAAAAAAAAAAAAA0AAAAdAAAALQAAAD0AAABNAAAA...   
33  WlpaWgAAAAAAAAAAAAAA0AAAAdAAAALQAAAD0AAABNAAAA...   
34  WlpaWgAAAAAAAAAAEgAAcAQABKAAAAAAAAAAAAAAAAAAAA...   

                         source  \
0   ./diff_depth.pcapng.parquet   
1        ./onoff.pcapng.parquet   
2        ./onoff.pcapng.parquet   
3        ./onoff.pcapng.parquet   
4        ./o

# Packets

In [56]:
for k in ["PreStopPacket-TBC","Packet 204 ./onoff.pcapng"]:
    print(np.array(df[df.desc == k].lst.iloc[0]),"-",k)

[15  7  3  6 48  0  0  0  0  0  0  0  1  0  0  0  4] - PreStopPacket-TBC
[15  7  3  6 48  0  0  0  0  0  0  0  1] - Packet 204 ./onoff.pcapng


In [55]:
for k in ["TGC-related-TBC-StartMaybe","StopAcq-TBC"]:
    print(np.array(df[df.desc == k].lst.iloc[0]),"-",k)
     

[  0   0   0   0   0   0   0   0   0   0   2 160] - TGC-related-TBC-StartMaybe
[  0   0   0   0   0   0   0   0   0   0   1 160] - StopAcq-TBC


# Others

In [38]:
B = np.array(df[df.desc == "ConfirmDepth1.2"].lst.iloc[0])
B

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 208,   0,
         0,   1, 208,   0,   0,   2, 208,   0,   0,   3, 208,   0,   0,
         4, 208,   0,   0,   5, 208,   0,   0,   6, 208,   0,   0,   7,
       208,   0,   0,   8, 208,   0,   0,   9, 208,   0,   0,  10, 208,
         0,   0,  11, 208,   0,   0,  12, 208,   0,   0,  13, 208,   0,
         0,  14, 208,   0,   0,  15, 208,   0,   0,  16, 208,   0,   0,
        17, 208,   0,   0,  18, 208,   0,   0,  19, 208,   0,   0,  20,
       208,   0,   0,  21, 208,   0,   0,  22, 208,   0,   0,  23, 208,
         0,   0,  24, 208,   0,   0,  25, 208,   0,   0,  26, 208,   0,
         0,  27, 208,   0,   0,  28, 208,   0,   0,  29, 208,   0,   0,
        30, 208,   0,   0,  31, 208,   0,   0,  32, 208,   0,   0,  33,
       208,   0,   0,  34, 208,   0,   0,  35, 208,   0,   0,  36, 208,
         0,   0,  37, 208,   0,   0,  38, 208,   0,   0,  39, 208,   0,
         0,  40, 208,   0,   0,  41, 208,   0,   0,  42, 208,   

In [39]:
A - B

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [47]:
for k in range(7):
    A = str(k+1)
    print(A,np.array(df[df.desc == "Seq1."+A].lst.iloc[0]))

1 [  0   0   0   0   0   0   0   0  12 139  18  96 180  45  64 128]
2 [  0   0   0   0   0   0   0   0  20   0   0 112   4   0   4 160]
3 [  0   0   0   0   0   0   0   0   0   0  16 179   0   0  32 179   0   0
  48 179   0   0  64 179]
4 [  0   0   0   0   0   0   0   0   0   0   0 208   0   0   1 208   0   0
   2 208   0   0   3 208   0   0   4 208   0   0   5 208   0   0   6 208
   0   0   7 208   0   0   8 208   0   0   9 208   0   0  10 208   0   0
  11 208   0   0  12 208   0   0  13 208   0   0  14 208   0   0  15 208
   0   0  16 208   0   0  17 208   0   0  18 208   0   0  19 208   0   0
  20 208   0   0  21 208   0   0  22 208   0   0  23 208   0   0  24 208
   0   0  25 208   0   0  26 208   0   0  27 208   0   0  28 208   0   0
  29 208   0   0  30 208   0   0  31 208   0   0  32 208   0   0  33 208
   0   0  34 208   0   0  35 208   0   0  36 208   0   0  37 208   0   0
  38 208   0   0  39 208   0   0  40 208   0   0  41 208   0   0  42 208
   0   0  43 208   0   0  44 20

In [50]:
for k in range(6):
    A = str(k+1)
    print(A,np.array(df[df.desc == "Init"+A].lst.iloc[0]))

1 [  0   0   0   0   0   0   0   0  24   0  16   0   5   4  17   0  10   5
  18   0   0 255  19   0   0   8  20   0   1   9  21   0   0  13  22   0
  15  14  23   0  48  15  24   0  32  16  25   0   6  17  26   0   8  18
  27   0   1  20  28   0   0  21  29   0   3  22  30   0   3  24  31   0
  85  25  32   0   5  26  33   0  85  27  34   0   5  28  35   0   0  33
  36   0   1  34  37   0  70  43  38   0   0  44  39   0   0  45  40   0
   1 255  41   0   2   0   0 144   9   0   0 112   0   0   3 160   2   0
   4 160  64   0   6 160]
2 []
3 [  0   0   0   0   0   0   0   0   1 210   0  32  96 198   1  32   0  64
   2  32  48  64   3  32  96  64   4  32 144  64   5  32 192  64   6  32
 240  64   7  32  16  65   8  32  64  65   9  32 112  65  10  32 192  65
  11  32  16  66  12  32  80  66  13  32 160  66  14  32 240  66  15  32
  48  67  16  32 128  67  17  32 192  67  18  32  16  68  19  32  80  68
  20  32 144  68  21  32 208  68  22  32  16  69  23  32  80  69  24  32
 144  69  25  32

In [42]:
np.array(df[df.desc == "Seq1.3"].lst.iloc[0])

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  16, 179,   0,
         0,  32, 179,   0,   0,  48, 179,   0,   0,  64, 179])